### ISSUE TITLE
Failed in X11 Linux

### ISSUE THREAD

**Issue by Shougo** [skanehira/deno-clippy#2]
```
% deno test -A --unstable
running 2 tests from ./mod_test.ts
image: write to/read from clipboard ... FAILED (135ms)
text: write to/read from clipboard ... FAILED (107ms)

 ERRORS

image: write to/read from clipboard => ./mod_test.ts:4:6
error: Error: The clipboard contents were not available in the requested format or the clipboard is empty.
    throw new Error(result.Error.error);
          ^
    at read_image (file:///home/shougo/src/deno-clippy/mod.ts:32:11)
    at file:///home/shougo/src/deno-clippy/mod_test.ts:9:35

text: write to/read from clipboard => ./mod_test.ts:14:6
error: Error: The clipboard contents were not available in the requested format or the clipboard is empty.
    throw new Error(result.Error.error);
          ^
    at read_text (file:///home/shougo/src/deno-clippy/mod.ts:16:11)
    at file:///home/shougo/src/deno-clippy/mod_test.ts:17:21

 FAILURES

image: write to/read from clipboard => ./mod_test.ts:4:6
text: write to/read from clipboard => ./mod_test.ts:14:6

FAILED | 0 passed | 2 failed (279ms)

error: Test failed
```

The latest version.

**Comment by skanehira** [comment]
Currently, arboard does not seem to work on Linux.
implemented fallback that use xclip in https://github.com/skanehira/deno-clippy/pull/3

**Comment by Shougo** [comment]
OK.  it works.
