### ISSUE TITLE
Issue when using write_text

### ISSUE THREAD

**Issue by cvburgess** [skanehira/deno-clippy#7]
```js
import { write_text } from "https://deno.land/x/clippy@v0.1.0/mod.ts";

await write_text("Foo");
```

```
error: Uncaught (in promise) TypeError: Deno.dlopen is not a function
  return Deno.dlopen(file, symbols);
              ^
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at async https://deno.land/x/clippy@v0.1.0/bindings/bindings.ts:51:14
```

**Comment by skanehira** [comment]
@cvburgess 
You have to use `--unstable` because FFI is not stable.

```sh
# NG
$ deno run -A sample.ts
error: Uncaught (in promise) TypeError: Deno.dlopen is not a function
  return Deno.dlopen(file, symbols);
              ^
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at async https://deno.land/x/clippy@v0.1.0/bindings/bindings.ts:51:14

# OK
$ deno run -A --unstable sample.ts 

```

**Comment by cvburgess** [comment]
Thanks! Any reason v1.25+ is not supported?

Im hesitant to switch back to this lib (currently using copy_paste) until it supports latest.

**Comment by skanehira** [comment]
@cvburgess 
> Thanks! Any reason v1.25+ is not supported?

This library uses Deno's FFI API, but the FFI API has breaking change since v1.25+
I'll support v1.25+, please wait a little bit :)

**Comment by skanehira** [comment]
@cvburgess Supported v1.25+ in #8 , Please update :)
